"""
Property test — FHIR round-trip fidelity.

Property 2 (Requirement 21.5):
    For any valid FHIR Observation or MedicationAdministration resource
    generated by Hypothesis strategies:
        parse(serialize(parse(input))) == parse(input)

The test uses the FHIRAdapter and serialize_to_fhir() from the ingestion service.
No database or network connections are required.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

import pytest
from hypothesis import HealthCheck, given, settings as h_settings
from hypothesis import strategies as st

from services.ingestion.adapters.fhir import FHIRAdapter, serialize_to_fhir
from shared.models import CanonicalRecord, LabRecord, MedicationRecord, VitalRecord

# ---------------------------------------------------------------------------
# Known LOINC codes that map to vitals and labs in loinc_map.json
# ---------------------------------------------------------------------------
_VITAL_LOINC = ["8310-5", "8867-4", "9279-1", "8480-6", "8462-4", "59408-5"]
_LAB_LOINC = ["26499-4", "6690-2", "731-0", "1988-5", "75241-0", "2524-7", "2160-0"]
_CHEMO_RXNORM = ["4492", "3002", "12574"]
_NORMAL_RXNORM = ["723", "1049502", "308460"]

# ---------------------------------------------------------------------------
# Hypothesis strategies for FHIR resources
# ---------------------------------------------------------------------------

_ts_strategy = st.datetimes(
    min_value=datetime(2020, 1, 1),
    max_value=datetime(2026, 1, 1),
    timezones=st.just(timezone.utc),
).map(lambda dt: dt.isoformat())

_patient_id_strategy = st.from_regex(r"patient-[a-z0-9]{6}", fullmatch=True)
_res_id_strategy = st.from_regex(r"res-[a-z0-9]{8}", fullmatch=True)
_value_strategy = st.floats(min_value=0.01, max_value=999.0, allow_nan=False, allow_infinity=False)


@st.composite
def fhir_observation_strategy(draw: Any) -> dict[str, Any]:
    """Generate a valid FHIR R4 Observation resource."""
    loinc = draw(st.sampled_from(_VITAL_LOINC + _LAB_LOINC))
    patient_id = draw(_patient_id_strategy)
    res_id = draw(_res_id_strategy)
    ts = draw(_ts_strategy)
    value = draw(_value_strategy)
    unit = draw(st.sampled_from(["mg/L", "10*9/L", "Cel", "/min", "mm[Hg]", "%"]))

    return {
        "resourceType": "Observation",
        "id": res_id,
        "status": "final",
        "code": {
            "coding": [{"system": "http://loinc.org", "code": loinc}]
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "effectiveDateTime": ts,
        "valueQuantity": {"value": value, "unit": unit},
    }


@st.composite
def fhir_medication_admin_strategy(draw: Any) -> dict[str, Any]:
    """Generate a valid FHIR R4 MedicationAdministration resource."""
    rxnorm = draw(st.sampled_from(_CHEMO_RXNORM + _NORMAL_RXNORM))
    patient_id = draw(_patient_id_strategy)
    res_id = draw(_res_id_strategy)
    ts = draw(_ts_strategy)
    dose = draw(_value_strategy)
    route = draw(st.sampled_from(["IV", "oral", "subcutaneous"]))
    drug_name = draw(st.sampled_from(["Cyclophosphamide", "Doxorubicin", "Paclitaxel", "Ibuprofen"]))

    return {
        "resourceType": "MedicationAdministration",
        "id": res_id,
        "status": "completed",
        "medicationCodeableConcept": {
            "coding": [
                {"system": "http://www.nlm.nih.gov/research/umls/rxnorm", "code": rxnorm},
            ],
            "text": drug_name,
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "effectiveDateTime": ts,
        "dosage": {
            "dose": {"value": dose, "unit": "mg"},
            "route": {"text": route},
        },
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

adapter = FHIRAdapter()


def _canonical_key(record: CanonicalRecord) -> dict[str, Any]:
    """Extract the fields that must be stable across round-trips."""
    p = record.payload
    base = {
        "patient_id": record.patient_id,
        "record_type": record.record_type,
        "source_record_id": record.source_record_id,
    }
    if isinstance(p, (VitalRecord, LabRecord)):
        base["loinc_code"] = p.loinc_code
        base["value_numeric"] = round(p.value_numeric, 6) if p.value_numeric is not None else None
    elif isinstance(p, MedicationRecord):
        base["rxnorm_code"] = p.rxnorm_code
        base["drug_name"] = p.drug_name
        base["is_chemotherapy"] = p.is_chemotherapy
        base["dose_mg"] = round(p.dose_mg, 6) if p.dose_mg is not None else None
    return base


def _parse_single(resource: dict[str, Any]) -> CanonicalRecord:
    raw = json.dumps(resource).encode()
    records = adapter.parse(raw)
    assert len(records) == 1, f"Expected 1 record, got {len(records)}"
    return records[0]


# ---------------------------------------------------------------------------
# Property 2: parse(serialize(parse(input))) == parse(input)
# ---------------------------------------------------------------------------

@given(resource=fhir_observation_strategy())
@h_settings(
    max_examples=200,
    suppress_health_check=[HealthCheck.too_slow],
    deadline=None,
)
def test_observation_roundtrip_idempotency(resource: dict[str, Any]) -> None:
    """
    Property 2 for Observation:
    parse(serialize(parse(input))) produces the same stable fields as parse(input).
    """
    first_parse = _parse_single(resource)
    fhir_out = serialize_to_fhir(first_parse)
    second_parse = _parse_single(fhir_out)

    assert _canonical_key(first_parse) == _canonical_key(second_parse), (
        f"Round-trip mismatch:\n"
        f"  first:  {_canonical_key(first_parse)}\n"
        f"  second: {_canonical_key(second_parse)}"
    )


@given(resource=fhir_medication_admin_strategy())
@h_settings(
    max_examples=200,
    suppress_health_check=[HealthCheck.too_slow],
    deadline=None,
)
def test_medication_roundtrip_idempotency(resource: dict[str, Any]) -> None:
    """
    Property 2 for MedicationAdministration:
    parse(serialize(parse(input))) produces the same stable fields as parse(input).
    """
    first_parse = _parse_single(resource)
    fhir_out = serialize_to_fhir(first_parse)
    second_parse = _parse_single(fhir_out)

    assert _canonical_key(first_parse) == _canonical_key(second_parse), (
        f"Round-trip mismatch:\n"
        f"  first:  {_canonical_key(first_parse)}\n"
        f"  second: {_canonical_key(second_parse)}"
    )


# ---------------------------------------------------------------------------
# Unit tests for edge cases
# ---------------------------------------------------------------------------

def test_observation_missing_loinc_adds_quality_flag() -> None:
    resource = {
        "resourceType": "Observation",
        "id": "obs-001",
        "status": "final",
        "code": {"coding": [{"system": "http://snomed.info/sct", "code": "12345"}]},
        "subject": {"reference": "Patient/p-001"},
        "effectiveDateTime": "2026-01-01T00:00:00+00:00",
        "valueQuantity": {"value": 37.2, "unit": "Cel"},
    }
    records = adapter.parse(json.dumps(resource).encode())
    assert len(records) == 1
    flags = records[0].data_quality_flags
    assert any(f.field_name == "loinc_code" for f in flags)


def test_bundle_parses_multiple_resources() -> None:
    bundle = {
        "resourceType": "Bundle",
        "type": "collection",
        "entry": [
            {"resource": {
                "resourceType": "Observation",
                "id": "obs-1",
                "status": "final",
                "code": {"coding": [{"system": "http://loinc.org", "code": "8310-5"}]},
                "subject": {"reference": "Patient/p-1"},
                "effectiveDateTime": "2026-01-01T00:00:00+00:00",
                "valueQuantity": {"value": 37.5, "unit": "Cel"},
            }},
            {"resource": {
                "resourceType": "MedicationAdministration",
                "id": "med-1",
                "status": "completed",
                "medicationCodeableConcept": {
                    "coding": [{"system": "http://www.nlm.nih.gov/research/umls/rxnorm", "code": "4492"}],
                    "text": "Cyclophosphamide",
                },
                "subject": {"reference": "Patient/p-1"},
                "effectiveDateTime": "2026-01-01T01:00:00+00:00",
                "dosage": {"dose": {"value": 500.0, "unit": "mg"}, "route": {"text": "IV"}},
            }},
        ],
    }
    records = adapter.parse(json.dumps(bundle).encode())
    assert len(records) == 2
    types = {r.record_type for r in records}
    assert "vital" in types or "lab" in types
    assert "medication" in types


def test_invalid_json_raises_422() -> None:
    from fastapi import HTTPException
    with pytest.raises(HTTPException) as exc_info:
        adapter.parse(b"not json at all")
    assert exc_info.value.status_code == 422


def test_missing_effective_datetime_raises_422() -> None:
    from fastapi import HTTPException
    resource = {
        "resourceType": "Observation",
        "id": "obs-bad",
        "status": "final",
        "code": {"coding": [{"system": "http://loinc.org", "code": "8310-5"}]},
        "subject": {"reference": "Patient/p-1"},
        # no effectiveDateTime
        "valueQuantity": {"value": 37.0, "unit": "Cel"},
    }
    with pytest.raises(HTTPException) as exc_info:
        adapter.parse(json.dumps(resource).encode())
    assert exc_info.value.status_code == 422
